x86_64:
  qemu:
    grub_commands:
      - serial --speed=115200
      - terminal_input serial console
      - terminal_output serial console
    kernel_arguments:
      - console=tty0
      - console=ttyS0,115200n8
