packages:
- kubelet-1.26.6
- kubeadm-1.26.6
- kubectl-1.26.6
- podman
- yq
- ignition-2.16.2
- keepalived
- cri-o-1.26.4
- kubernetes-imgs-1.26.6

add-files:
- ["systemd/update-ca-trust.service", "/usr/lib/systemd/system/update-ca-trust.service"]
- ["systemd/update-ca-trust.path", "/usr/lib/systemd/system/update-ca-trust.path"]
- ["systemd/ocne-disable-ignition.service", "/usr/lib/systemd/system/ocne-disable-ignition.service"]
- ["systemd/ocne.service", "/usr/lib/systemd/system/ocne.service"]
- ["systemd/ocne.sh", "/etc/ocne/ocne.sh"]
- ["systemd/ocne-update.service", "/usr/lib/systemd/system/ocne-update.service"]
- ["systemd/ocne-update.sh", "/etc/ocne/ocne-update.sh"]
- ["systemd/ocne-image-cleanup.service", "/usr/lib/systemd/system/ocne-image-cleanup.service"]
- ["systemd/ocne-image-cleanup.sh", "/etc/ocne/ocne-image-cleanup.sh"]
- ["systemd/ocne-reset.service", "/usr/lib/systemd/system/ocne-reset.service"]
- ["systemd/ocne-reset.sh", "/etc/ocne/ocne-reset.sh"]
- ["systemd/ocne-kube-update.sh", "/etc/ocne/ocne-kube-update.sh"]
- ["systemd/ocne-kubeadm-upgrade.sh", "/etc/ocne/ocne-kubeadm-upgrade.sh"]
- ["systemd/ocne-prune.service", "/usr/lib/systemd/system/ocne-prune.service"]
- ["systemd/ocne-prune.sh", "/etc/ocne/ocne-prune.sh"]
- ["systemd/kube-update.conf", "/etc/systemd/system/kubelet.service.d/kube-update.conf"]
- ["files/crio.conf", "/etc/crio/crio.conf"]
- ["files/kubeadm-default.conf", "/etc/ocne/kubeadm-default.conf"]
- ["files/check-node-health.sh", "/usr/bin/check-node-health.sh"]
- ["files/rescue.sh", "/usr/bin/rescue.sh"]
- ["files/storage.conf", "/etc/containers/storage.conf"]
- ["systemd/usr-lib-opt-cni-bin.mount", "/etc/systemd/system/usr-lib-opt-cni-bin.mount"]
- ["dracut-modules/module-setup.sh", "/usr/lib/dracut/modules.d/35ocne/module-setup.sh"]
- ["dracut-modules/grow-rootfs.sh", "/usr/lib/dracut/modules.d/35ocne/grow-rootfs.sh"]
- ["dracut-modules/grow-rootfs.service", "/usr/lib/dracut/modules.d/35ocne/grow-rootfs.service"]
- ["dracut-modules/make-rootfs.sh", "/usr/lib/dracut/modules.d/35ocne/make-rootfs.sh"]
- ["dracut-modules/make-rootfs.service", "/usr/lib/dracut/modules.d/35ocne/make-rootfs.service"]

units:
- ocne-disable-ignition.service
- ocne.service
- ocne-prune.service
- ocne-update.service
- ocne-image-cleanup.service
- ocne-nginx.service
- keepalived.service
- usr-lib-opt-cni-bin.mount

postprocess:
- rm /etc/cni/net.d/100-crio-bridge.conf
- groupadd -r keepalived_script
- useradd -r -s /sbin/nologin -g keepalived_script -M keepalived_script
